apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to NGINX Latest</title>
    </head>
    <body>
        <h1>FIFA 2024</h1>
        <p>This page is served from a ConfigMap.</p>
    </body>
    </html>
