apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
  labels:
    app: nginx
  annotations:
    configmap-version: "1"
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
  volumes:
   - name: nginx-html
     configMap:
        name: nginx-index
