apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapp
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # List of namespaces
          - list:
              elements:
                - namespace: leasepoint-dev
                  env: dev
                - namespace: leasepoint-qa
                  env: qa
          # List of APIs
          - list:
              elements:
                - name: lp-coreapi
                # - name: lp-masterdatapi
                # - name: lp-gridsapi
                # - name: lp-iamapi
                # - name: lp-logapi
                # - name: lp-tntcatlogapi


  template:
    metadata:
      name: '{{name}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:danish21385/gitops.git
        targetRevision: main
        path: helm-charts/v10
        helm:
          valueFiles:       
            - ../../values/{{name}}/values-{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true            # Auto-create namespace if it doesn't exist
          - PruneLast=true                  # Prune resources only after applying all changes
          - ApplyOutOfSyncOnly=true         # Apply only out-of-sync resources
          - Validate=false                  # Skip resource validation before apply
          - RespectIgnoreDifferences=true   # Skip syncing fields listed under ignoreDifferences
          - Replace=true                    # Use kubectl replace instead of apply
          - ServerSideApply=true            # Use server-side apply instead of client-side
          - FailOnSharedResource=true       # Fail sync if shared resources exist
          - PrunePropagationPolicy=foreground  # Control pruning behavior
          - PruneLast=true                  # Wait to prune until all apply operations succeed
          - ApplyOnly=true                  # Don’t prune, just apply
        automated:
          prune: true
          selfHeal: true