apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-index
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
data:
  index.html: {{ .Values.index.indexHtml | toYaml | indent 1 }}