apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-qa
  namespace: argocd
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mychart/qa
    repoURL: git@github.com:danish21385/gitops.git
    targetRevision: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  automated:
      prune: true
      selfHeal: true