apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "rootchart.fullname" . }}-dev
  labels:
  {{- include "rootchart.labels" . | nindent 4 }}
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mychart/dev
    repoURL: git@github.com:danish21385/gitops.git
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true